### ISSUE TITLE
use setupRemixContext inside a default remix server

### ISSUE THREAD

**Issue by eliawk** [ITenthusiasm/remix-supertokens#6]
Hello,
is it possibile to use the **setupRemixContext** inside a standard remix server instead of using a custom one?

tx

**Comment by ITenthusiasm** [comment]
Hey @eliawk! It's certainly possible to perform authentication that is _similar_ to what `setupRemixContext` does using `@remix-run/serve`. However, `setupRemixContext` is designed to work with Express Middleware and `getLoadContext` -- neither of which are accessible to developers using `@remix-run/serve`. So you wouldn't be able to use that function in the exact same way. When you need more than what the standard Remix Server provides, the recommendation from the docs and from Discord seems to be to just use an Express server. But if you prefer not to do that, there is another alternative:

You can create a Higher Order Function (HOF) that accepts a server function (an `action` or a `loader`). This HOF would perform authentication based on the `Request` information. If authentication succeeds, it will pass the user data to the server function that it receives as an argument. If authentication fails, the HOC can redirect the user to the proper location. Below is some rough example code, but it is _untested_. The code below is only intended to get you started. (Feel free to ask questions if you run into trouble, though.)

```ts
// In `requestHelpers.ts`

import type { ActionFunction, LoaderFunction, LoaderFunctionArgs, ActionFunctionArgs } from "@remix-run/node";
import Session from "supertokens-node/recipe/session";
import { parse } from "cookie";
import { authCookieNames, createHeadersFromTokens } from "~/.server/supertokens/cookieHelpers";
import { commonRoutes } from "~/utils/constants";

type UserInfo = { id: string };

export function withAuthentication<
  T extends (
    user: UserInfo | undefined,
    args: LoaderFunctionArgs | ActionFunctionArgs,
  ) => ReturnType<LoaderFunction> | ReturnType<ActionFunction>,
>(
  serverFunction?: T,
): (requestData: Parameters<T>[1]) => Promise<ReturnType<T> extends Promise<infer U> ? U : ReturnType<T>> {
  return async (requestData) => {
    try {
      const cookies = parse(requestData.request.headers.get("Cookie") ?? "");
      const accessToken = cookies[authCookieNames.access] ?? "";
      const antiCsrfToken = cookies[authCookieNames.csrf];
      const session = await Session.getSessionWithoutRequestResponse(accessToken, antiCsrfToken);
      const userId = session.getUserId();

      type ServerFunctionReturnType = ReturnType<T> extends Promise<infer U> ? U : ReturnType<T>;
      const user = userId ? { id: userId } : undefined;
      return (serverFunction?.(user, requestData) ?? null) as ServerFunctionReturnType;
    } catch (error) {
      if (!Session.Error.isErrorFromSuperTokens(error)) {
        throw new Response("An unexpected error occurred", { status: 500 });
      }

      // URL Details
      const { request } = requestData;
      const url = new URL(request.url);
      const isDataRequest = url.searchParams.has("_data");
      if (isDataRequest) url.searchParams.delete("_data");

      const userNeedsSessionRefresh = error.type === Session.Error.TRY_REFRESH_TOKEN;
      const basePath = userNeedsSessionRefresh ? commonRoutes.refreshSession : commonRoutes.login;
      const returnUrl = encodeURI(`${url.pathname}${url.search}`);
      const redirectUrl = `${basePath}?returnUrl=${returnUrl}`;

      // Redirect the user to the proper auth page. Delete their tokens if they don't need to attempt a token refresh.
      const headers = userNeedsSessionRefresh ? new Headers() : createHeadersFromTokens({});
      headers.set(isDataRequest ? "x-remix-redirect" : "Location", redirectUrl);

      if (isDataRequest) throw new Response(null, { status: 204, headers });
      throw new Response(null, { status: userNeedsSessionRefresh ? 307 : 303, headers });
    }
  };
}
```

You could then use this HOF to add authentication to any server function

```tsx
// In some route file ...

export const loader = withAuthentication((user, { request }) => {
  // ...
});

export const action = withAuthentication(async (user, { request }) => {
  // ...
});
```

If you want to protect a page that doesn't need to fetch any data, you can just call `withAuthentication` without any arguments.

```ts
export const loader = withAuthentication();
```

Note that you will still have to initialize `SuperTokens` in a central location to get this working, and that initialization should only happen once during the lifetime of the application. Additionally, you don't have to `throw` error `Responses` if you don't want to, though it `throw`ing is recommended here.

Notice that there is no `requestAllowed` logic in this HOF (compared to `setupRemixContext`). This is a HOF that you'll need to use on _every_ server function that you want to be authenticated. Therefore, any server function that isn't wrapped in this HOF will automatically be public.

---

Let me know if you have any additional questions.

**Comment by ITenthusiasm** [comment]
There might be a way to get the job done with [`entry.server.tsx`](https://remix.run/docs/en/main/file-conventions/entry.server) as well. I have not explored that option yet. You'd have to account for both regular Browser Requests and Data Requests if you try to go that route, however. You'd also have to try to find a way to pass user data through -- if that's possible. (I'm not sure that such a thing _is_ possible.)

**Comment by ITenthusiasm** [comment]
Hey @eliawk, I haven't heard back from you in about 2 weeks, so I'm going to close the issue for now. Feel free to re-open it if you have any other problems or concerns. Thanks!
