### ISSUE TITLE
what are those out-of-project source files?

### ISSUE THREAD

**Issue by lixin-dev** [ITenthusiasm/remix-supertokens#7]
```
import Header, { headerStyles } from "~/components/Header";
import { authPages } from "~/utils/constants.js";

// Styles
import globalStyles from "~/styles/shared/global.css?url";
```

where are those files?

**Comment by lixin-dev** [comment]
solved by replacing ~ with .. or .

**Comment by ITenthusiasm** [comment]
@xin-at-marathon Yeah, if you're familiar with Linux systems, `~` doesn't mean quite the same thing in Remix. :sweat_smile: If you look at the [tsconfig.json](https://github.com/ITenthusiasm/remix-supertokens/blob/main/tsconfig.json#L19), it's simply a way to point to other files in the `app` directory when importing modules -- without having to do a lot of `../../../../../../../path`.
